name: pam_p7_2026_ifs23055_dongeng
description: "Aplikasi Dongeng Anak dengan Flutter Networking."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  image_picker: ^1.1.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/